---
# Script of demo for sellyoursaas ansible use.
#
# To run the script:
# ansible-playbook update_sellyoursaas_conf.yml
#

- name: Update an entry into sellyoursaas.conf
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"