---
# Script to run apt install command on servers
#
# To run the script:
# ansible-playbook -K launch_apt_install.yml -i hosts-xxx -e 'target=targethost'
# ansible-playbook -K launch_apt_install.yml -i hosts-xxx -e 'target=targethost php74=1' --limit=*.mydomain.com
#


- name: Apt install packages
  hosts: '{{target}}'
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: Launch apt for main packages
    apt:
      pkg:
      - php7.4 
      - php7.4-cli 
      - libapache2-mod-php7.4 
      - php7.4-fpm 
      - php7.4-gd 
      - php7.4-imap 
      - php7.4-json 
      - php7.4-ldap 
      - php7.4-mysql 
      - php7.4-curl 
      - php7.4-memcached 
      - php7.4-imagick 
      - php7.4-geoip 
      - php7.4-intl 
      - php7.4-xml 
      - php7.4-zip 
      - php7.4-bz2 
      - php7.4-ssh2 
      - php7.4-mbstring 
      - php7.4-dev 
    register: command_output
    when: 
      - php74 is defined

  - debug:
      var: command_output.stdout_lines
    
  - name: Launch apt for GLPI packages
    apt:
      pkg:
      - php7.4-readline
      - php7.4-xmlrpc
    register: command_output
    when: 
      - php74 is defined
      
  - debug:
      var: command_output.stdout_lines

      
  - name: Launch apt for misc packages
    apt:
      pkg:
      - snapd
      - acl
    register: command_output

      